// Task 3 — AI blind test generation.
//
// Everything below this comment was generated by an AI assistant that was
// given ONLY the signature of ValidateEmail (no implementation, no existing
// tests, no access to this repository). I did not edit the generated code,
// I only added this header. See ai-blind-testing/REPORT.md for the prompt,
// the results of running it against my implementation, and what I changed
// because of it.
package validate

import (
	"strings"
	"testing"
)

func TestValidateEmail_AI(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  bool
	}{
		// --- valid addresses ---
		{name: "simple address", input: "user@example.com", want: true},
		{name: "single character local part", input: "a@example.com", want: true},
		{name: "digits only local part", input: "12345@example.com", want: true},
		{name: "dot in local part", input: "first.last@example.com", want: true},
		{name: "plus tag in local part", input: "user+tag@example.com", want: true},
		{name: "hyphen in local part", input: "first-last@example.com", want: true},
		{name: "underscore in local part", input: "first_last@example.com", want: true},
		{name: "mixed case", input: "First.Last@Example.COM", want: true},
		{name: "subdomain", input: "user@mail.example.com", want: true},
		{name: "multiple subdomains", input: "user@a.b.c.example.com", want: true},
		{name: "hyphen in domain", input: "user@my-domain.com", want: true},
		{name: "digits in domain", input: "user@mail123.example.com", want: true},
		{name: "country code second level domain", input: "user@example.co.uk", want: true},
		{name: "long tld", input: "user@example.technology", want: true},
		{name: "punycode idn domain", input: "user@xn--80ak6aa92e.com", want: true},
		{name: "local part at 64 char limit", input: strings.Repeat("a", 64) + "@example.com", want: true},
		{name: "domain label at 63 char limit", input: "user@" + strings.Repeat("a", 63) + ".com", want: true},
		{name: "total length at 254 char limit", input: strings.Repeat("a", 64) + "@" + strings.Repeat("b", 63) + "." + strings.Repeat("c", 63) + "." + strings.Repeat("d", 57) + ".com", want: true},

		// --- empty input and whitespace ---
		{name: "empty string", input: "", want: false},
		{name: "only whitespace", input: "   ", want: false},
		{name: "leading whitespace", input: " user@example.com", want: false},
		{name: "trailing whitespace", input: "user@example.com ", want: false},
		{name: "space in local part", input: "first last@example.com", want: false},
		{name: "space in domain", input: "user@exam ple.com", want: false},
		{name: "tab in local part", input: "first\tlast@example.com", want: false},
		{name: "trailing newline", input: "user@example.com\n", want: false},

		// --- missing parts ---
		{name: "missing at sign", input: "user.example.com", want: false},
		{name: "only at sign", input: "@", want: false},
		{name: "missing local part", input: "@example.com", want: false},
		{name: "missing domain", input: "user@", want: false},
		{name: "missing tld", input: "user@localhost", want: false},
		{name: "empty tld after dot", input: "user@example.", want: false},
		{name: "multiple at signs", input: "user@@example.com", want: false},
		{name: "at sign in both parts", input: "first@last@example.com", want: false},

		// --- dots ---
		{name: "leading dot in local part", input: ".user@example.com", want: false},
		{name: "trailing dot in local part", input: "user.@example.com", want: false},
		{name: "consecutive dots in local part", input: "first..last@example.com", want: false},
		{name: "leading dot in domain", input: "user@.example.com", want: false},
		{name: "trailing dot in domain", input: "user@example.com.", want: false},
		{name: "consecutive dots in domain", input: "user@example..com", want: false},

		// --- special characters ---
		{name: "comma in local part", input: "first,last@example.com", want: false},
		{name: "semicolon in domain", input: "user@exam;ple.com", want: false},
		{name: "parentheses in local part", input: "user(comment)@example.com", want: false},
		{name: "unbalanced quote in local part", input: "user\"name@example.com", want: false},
		{name: "angle brackets around address", input: "<user@example.com>", want: false},
		{name: "display name with address", input: "John Doe <john@example.com>", want: false},
		{name: "mailto prefix", input: "mailto:user@example.com", want: false},
		{name: "underscore in domain", input: "user@my_domain.com", want: false},
		{name: "leading hyphen in domain label", input: "user@-example.com", want: false},
		{name: "null byte in local part", input: "user\x00@example.com", want: false},

		// --- unicode ---
		{name: "non ascii local part", input: "пользователь@example.com", want: false},
		{name: "non ascii domain", input: "user@exämple.com", want: false},
		{name: "invalid utf8 sequence", input: "user@exam\xffple.com", want: false},

		// --- length limits ---
		{name: "local part over 64 chars", input: strings.Repeat("a", 65) + "@example.com", want: false},
		{name: "address over maximum total length", input: strings.Repeat("a", 64) + "@" + strings.Repeat("b", 63) + "." + strings.Repeat("c", 63) + "." + strings.Repeat("d", 63) + "." + strings.Repeat("e", 63) + ".com", want: false},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := ValidateEmail(tc.input)
			if got != tc.want {
				t.Errorf("ValidateEmail(%q) = %v, want %v", tc.input, got, tc.want)
			}
		})
	}
}
